INSERT INTO internship_periods (id, start_date, end_date, registration_start_date, registration_end_date, status, description, created_at, updated_at, deleted_at) VALUES
('2024.1', '2024-01-15', '2024-04-15', '2023-12-01', '2023-12-31', 'END', 'Kỳ thực tập học kỳ 1 năm học 2023-2024', NOW(), NOW(), NULL),
('2024.2', '2024-05-01', '2024-07-31', '2024-04-01', '2024-04-20', 'ACTIVE', 'Kỳ thực tập học kỳ 2 năm học 2023-2024', NOW(), NOW(), NULL),
('2025.1', '2024-09-01', '2024-12-15', '2024-08-01', '2024-08-20', 'UPCOMING', 'Kỳ thực tập học kỳ 1 năm học 2024-2025', NOW(), NOW(), NULL);

INSERT INTO internship_positions (id, company_id, period_id, title, description, requirements, benefits, available_slots, registered_count, work_type, due_date, created_at, updated_at, deleted_at) VALUES
(1, 1, '2024.2', 'Java Developer Intern', 'Tham gia phát triển các ứng dụng web sử dụng Java Spring và Vue.js', 'Sinh viên năm cuối ngành CNTT, có kiến thức cơ bản về Java, HTML/CSS, JavaScript', 'Được hướng dẫn bởi các kỹ sư có kinh nghiệm, có cơ hội làm việc chính thức sau khi tốt nghiệp, trợ cấp 5 triệu/tháng', 5, 2, 'FULL_TIME', '2024-04-25', NOW(), NOW(), NULL),
(2, 1, '2024.2', 'Frontend Developer Intern', 'Tham gia phát triển giao diện người dùng cho các ứng dụng web và mobile', 'Sinh viên năm cuối ngành CNTT, có kiến thức về HTML/CSS, JavaScript, ReactJS hoặc Vue.js', 'Được hướng dẫn bởi các kỹ sư có kinh nghiệm, có cơ hội làm việc chính thức sau khi tốt nghiệp, trợ cấp 4.5 triệu/tháng', 3, 1, 'FULL_TIME', '2024-04-25', NOW(), NOW(), NULL),
(3, 2, '2024.2', 'Software Engineer Intern', 'Tham gia phát triển các sản phẩm phần mềm trong lĩnh vực viễn thông', 'Sinh viên năm cuối ngành CNTT hoặc Điện tử Viễn thông, có kiến thức về lập trình C/C++, Java', 'Được làm việc trong môi trường chuyên nghiệp, có cơ hội trải nghiệm các công nghệ mới, trợ cấp 5 triệu/tháng', 4, 1, 'FULL_TIME', '2024-04-20', NOW(), NOW(), NULL),
(4, 3, '2024.2', 'Network Engineer Intern', 'Hỗ trợ đội ngũ kỹ thuật trong việc vận hành và phát triển hệ thống mạng', 'Sinh viên năm cuối ngành CNTT hoặc Điện tử Viễn thông, có kiến thức về mạng máy tính, TCP/IP', 'Được đào tạo về các công nghệ mạng mới nhất, tiếp xúc với hệ thống mạng quy mô lớn, trợ cấp 4 triệu/tháng', 2, 1, 'FULL_TIME', '2024-04-15', NOW(), NOW(), NULL),
(5, 4, '2024.2', 'Software Tester Intern', 'Tham gia đội ngũ kiểm thử phần mềm, phát triển và thực hiện các kịch bản kiểm thử', 'Sinh viên năm cuối ngành CNTT, có kiến thức cơ bản về quy trình phát triển phần mềm, có tư duy logic tốt', 'Được đào tạo về kiểm thử phần mềm, làm việc trong môi trường chuyên nghiệp, trợ cấp 4 triệu/tháng', 3, 1, 'FULL_TIME', '2024-04-30', NOW(), NOW(), NULL),
(6, 5, '2024.2', 'Data Engineer Intern', 'Tham gia vào việc thu thập, xử lý và phân tích dữ liệu lớn', 'Sinh viên năm cuối ngành CNTT hoặc Toán Tin, có kiến thức về SQL, Python, và các công cụ xử lý dữ liệu', 'Được làm việc với dữ liệu thực tế quy mô lớn, được hướng dẫn bởi các chuyên gia dữ liệu, trợ cấp 5.5 triệu/tháng', 2, 0, 'FULL_TIME', '2024-04-28', NOW(), NOW(), NULL),
(7, 6, '2024.2', 'Cloud Engineer Intern', 'Hỗ trợ đội ngũ kỹ thuật trong việc triển khai và quản lý các dịch vụ đám mây', 'Sinh viên năm cuối ngành CNTT, có kiến thức về cloud computing, hiểu biết cơ bản về AWS hoặc Azure', 'Được làm việc với các công nghệ đám mây hiện đại, được đào tạo về các dịch vụ Microsoft, trợ cấp 6 triệu/tháng', 2, 0, 'FULL_TIME', '2024-04-25', NOW(), NOW(), NULL),
(8, 7, '2024.2', 'Machine Learning Intern', 'Tham gia vào các dự án ứng dụng machine learning trong các sản phẩm của Google', 'Sinh viên năm cuối ngành CNTT hoặc Toán Tin, có kiến thức về machine learning, Python, và TensorFlow', 'Được làm việc với các kỹ sư hàng đầu, tiếp xúc với dữ liệu thực tế quy mô lớn, trợ cấp 7 triệu/tháng', 1, 0, 'FULL_TIME', '2024-04-20', NOW(), NOW(), NULL);

INSERT INTO internship_applications (id, student_id, position_id, period_id, preference_order, status, cv_id, note, updated_at, deleted_at, created_at) VALUES
(1, 1, 1, '2024.2', 1, 'APPROVED', 2, 'Em rất mong muốn được thực tập tại FPT Software để phát triển kỹ năng lập trình Java', NOW(), NULL, DATE_SUB(NOW(), INTERVAL 15 DAY)),
(2, 1, 2, '2024.2', 2, 'CANCELLED', 2, 'Em cũng quan tâm đến vị trí Frontend Developer', NOW(), NULL, DATE_SUB(NOW(), INTERVAL 15 DAY)),
(3, 2, 3, '2024.2', 1, 'APPROVED', 3, 'Em mong muốn được thực tập tại Viettel để học hỏi thêm về phát triển phần mềm trong môi trường doanh nghiệp lớn', NOW(), NULL, DATE_SUB(NOW(), INTERVAL 13 DAY)),
(4, 3, 4, '2024.2', 1, 'APPROVED', 4, 'Em quan tâm đến lĩnh vực mạng và muốn được thực tập tại VNPT', NOW(), NULL, DATE_SUB(NOW(), INTERVAL 12 DAY)),
(5, 4, 5, '2024.2', 1, 'PENDING', 5, 'Em mong muốn được thực tập tại MISA để học hỏi về quy trình kiểm thử chuyên nghiệp', NOW(), NULL, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(6, 5, 1, '2024.2', 1, 'PENDING', 6, 'Em có kinh nghiệm với Java và Spring Boot qua các dự án ở trường đại học', NOW(), NULL, DATE_SUB(NOW(), INTERVAL 8 DAY));

INSERT INTO external_internships (id, student_id, period_id, confirmation_file_path, status, created_at, updated_at) VALUES
(1, 6, '2024.2', '/uploads/confirmations/20216345/confirmation_letter.pdf', 'APPROVED', DATE_SUB(NOW(), INTERVAL 10 DAY), NOW()),
(2, 7, '2024.2', '/uploads/confirmations/20216678/confirmation_letter.pdf', 'PENDING', DATE_SUB(NOW(), INTERVAL 5 DAY), NOW()),
(3, 8, '2024.2', '/uploads/confirmations/20216901/confirmation_letter.pdf', 'PENDING', DATE_SUB(NOW(), INTERVAL 3 DAY), NOW());

INSERT INTO internship_progress (id, student_id, position_id, period_id, teacher_id, start_date, end_date, is_external, external_id, status, supervisor_name, supervisor_position, supervisor_email, supervisor_phone, teacher_confirmed, teacher_confirmed_at, created_at, updated_at, deleted_at) VALUES
(1, 1, 1, '2024.2', 1, '2024-05-01', '2024-07-31', false, NULL, 'IN_PROGRESS', 'Nguyễn Văn Hải', 'Senior Java Developer', 'hai.nv@fpt.com.vn', '0987654321', true, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), NOW(), NULL),
(2, 2, 3, '2024.2', 2, '2024-05-01', '2024-07-31', false, NULL, 'IN_PROGRESS', 'Trần Minh Tuấn', 'Project Manager', 'tuan.tm@viettel.com.vn', '0987654322', true, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), NOW(), NULL),
(3, 3, 4, '2024.2', 3, '2024-05-01', '2024-07-31', false, NULL, 'IN_PROGRESS', 'Lê Văn Bình', 'Network Manager', 'binh.lv@vnpt.com.vn', '0987654323', true, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY), NOW(), NULL),
(4, 6, NULL, '2024.2', 4, '2024-05-01', '2024-07-31', true, 1, 'IN_PROGRESS', 'Đỗ Thị Hương', 'HR Director', 'huong.dt@nab.com.vn', '0987654324', true, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), NOW(), NULL);
