version: '3.8'

services:
  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - microservices-network

  mysql-position:
    image: mysql:8.0
    container_name: mysql-position
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: position_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - microservices-network

  mysql-registration:
    image: mysql:8.0
    container_name: mysql-registration
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registration_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    networks:
      - microservices-network

  mysql-internship:
    image: mysql:8.0
    container_name: mysql-internship
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: internship_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    networks:
      - microservices-network

  mysql-evaluation:
    image: mysql:8.0
    container_name: mysql-evaluation
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evaluation_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3311:3306"
    networks:
      - microservices-network

  mysql-notification:
    image: mysql:8.0
    container_name: mysql-notification
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3312:3306"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
