-- Insert admin records with auth_user_id 1, 2
INSERT INTO admins (id, auth_user_id, name, department, position, image_path, created_at, updated_at) VALUES
                                                                                                          (1, 1, 'Admin User 1', 'System Administration', 'Admin Manager', '/uploads/avatars/admin/1_5230f6cd-5033-4f09-9f6b-b365972cad4b.png', NOW(), NOW()),
                                                                                                          (2, 2, 'Admin User 2', 'IT Operations', 'System Administrator', '/uploads/avatars/admin/2_b4193a88-5967-450f-8bce-e74dfc425725.png', NOW(), NOW());

-- Insert teacher records with auth_user_id 3-6
INSERT INTO teachers (id, auth_user_id, name, department, position, image_path, created_at, updated_at) VALUES
                                                                                                            (1, 3, 'TS. Vũ Thành Minh', 'Khoa Toán - Tin học', 'Giảng viên', '/uploads/avatars/teacher/3_fe3d85ff-4431-447e-aae5-1a8c255c26cc.png', NOW(), NOW()),
                                                                                                            (2, 4, 'TS. Nguyễn Trung Hoàng', 'Khoa Toán - Tin học', 'Giảng viên', '/uploads/avatars/teacher/4_5e063f01-3e64-4e2f-8d22-4a8e3f370e05.png', NOW(), NOW()),
                                                                                                            (3, 5, 'PGS.TS. Lê Đình Hưng', 'Khoa Toán - Tin học', 'Phó Trưởng khoa', '/uploads/avatars/teacher/5_740574dd-a501-4ee0-bb70-a1d58bd74ba6.png', NOW(), NOW()),
                                                                                                            (4, 6, 'ThS. Phạm Văn Cường', 'Khoa Toán - Tin học', 'Giảng viên', '/uploads/avatars/teacher/6_ba8dff36-6379-4730-a916-3db27f82d6b4.png', NOW(), NOW());

-- Insert companies first since company_contacts reference them
INSERT INTO companies (id, name, short_name, is_foreign_company, tax_code, website, address, business_type, description, founding_year, employee_count, capital, logo_path, is_verified, is_linked, created_at, updated_at) VALUES
                                                                                                                                                                                                                                (1, 'FPT Software', 'Công ty TNHH Phần mềm FPT', false, '0101248141', 'https://fptsoftware.com', 'Tòa nhà FPT, Phạm Hùng, Cầu Giấy, Hà Nội', 'Công nghệ thông tin', 'FPT Software là công ty thành viên của Tập đoàn FPT, một trong những công ty công nghệ thông tin hàng đầu Việt Nam.', 1999, 20000, 5000000000, '/uploads/company/8_7d2b9f11-414c-4327-b5b4-fa2c0377f064.png', true, true, NOW(), NOW()),
                                                                                                                                                                                                                                (2, 'Viettel', 'Tập đoàn Công nghiệp - Viễn thông Quân đội', false, '0100109106', 'https://viettel.com.vn', 'Số 1 Giang Văn Minh, Kim Mã, Ba Đình, Hà Nội', 'Viễn thông', 'Tập đoàn Công nghiệp - Viễn thông Quân đội (Viettel) là tập đoàn viễn thông lớn nhất Việt Nam.', 1989, 70000, 300000000000, '/uploads/company/10_4c4298c0-2f42-4e37-9654-4cb793f5b1ef.png', true, true, NOW(), NOW()),
                                                                                                                                                                                                                                (3, 'VNPT', 'Tập đoàn Bưu chính Viễn thông Việt Nam', false, '0100684378', 'https://vnpt.com.vn', 'Số 57 Huỳnh Thúc Kháng, Láng Hạ, Đống Đa, Hà Nội', 'Viễn thông', 'Tập đoàn Bưu chính Viễn thông Việt Nam (VNPT) là doanh nghiệp nhà nước cung cấp dịch vụ bưu chính viễn thông.', 1995, 50000, 200000000000, '/uploads/company/11_8f9c8ee6-0afd-4f4f-bb54-cdcac7959873.png', true, true, NOW(), NOW()),
                                                                                                                                                                                                                                (4, 'MISA', 'Công ty Cổ phần MISA', false, '0101243150', 'https://misa.com.vn', 'Tòa nhà Technosoft, Phố Duy Tân, Cầu Giấy, Hà Nội', 'Phần mềm', 'MISA là công ty phát triển và cung cấp phần mềm quản lý, kế toán hàng đầu tại Việt Nam.', 1994, 2000, 50000000000, '/uploads/company/12_8e3a582d-75c4-45a0-8334-43474af7e8a5.png', true, true, NOW(), NOW()),
                                                                                                                                                                                                                                (5, 'CMC Global', 'Công ty Cổ phần CMC Global', false, '0107267567', 'https://cmcglobal.com.vn', 'Tòa nhà CMC, Duy Tân, Cầu Giấy, Hà Nội', 'Công nghệ thông tin', 'CMC Global là đơn vị thành viên của Tập đoàn Công nghệ CMC, chuyên cung cấp dịch vụ phát triển phần mềm chất lượng cao.', 2017, 1500, 40000000000, '/uploads/company/13_515ba838-9eb7-4ea5-903e-0fd1409a2960.jpg', true, true, NOW(), NOW()),
                                                                                                                                                                                                                                (6, 'Microsoft Vietnam', 'Microsoft Vietnam LLC', true, NULL, 'https://microsoft.com', 'Tòa nhà Keangnam, Phạm Hùng, Nam Từ Liêm, Hà Nội', 'Công nghệ thông tin', 'Microsoft Vietnam là văn phòng đại diện của tập đoàn Microsoft tại Việt Nam.', 1975, 150000, 1000000000000, '/uploads/company/14_6ffc132b-d627-4585-b43d-b8607526bccb.png', true, true, NOW(), NOW()),
                                                                                                                                                                                                                                (7, 'Google Vietnam', 'Google Asia Pacific Pte. Ltd.', true, NULL, 'https://google.com', 'Tòa nhà BitexcoFinancial, Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh', 'Công nghệ thông tin', 'Google Vietnam cung cấp các dịch vụ tìm kiếm, quảng cáo và các sản phẩm công nghệ khác.', 1998, 135000, 900000000000, '/uploads/company/15_e311e1e9-3765-4197-89ef-619485dddf30.png', true, true, NOW(), NOW());

-- Insert company_contacts with auth_user_id 7-15
INSERT INTO company_contacts (id, company_id, name, position, auth_user_id, image_path, created_at, updated_at) VALUES
                                                                                                                    (1, 1, 'Nguyễn Thị Hương', 'HR Manager', 7, '/uploads/avatars/company-contact/7_1844fa19-191a-48b6-bcd4-3fe7ac24d9b5.png', NOW(), NOW()),
                                                                                                                    (2, 1, 'Phạm Văn Nam', 'Talent Acquisition', 8, '/uploads/avatars/company-contact/8_385a57ff-9a5f-47ac-b63e-0442e604be49.png', NOW(), NOW()),
                                                                                                                    (3, 2, 'Trần Văn Hùng', 'HR Director', 9, '/uploads/avatars/company-contact/9_715d68cc-1ac7-4199-b991-cf3577ca8c91.png', NOW(), NOW()),
                                                                                                                    (4, 2, 'Lê Thị Mai', 'Recruiter', 10, '/uploads/avatars/company-contact/10_421c41b0-dd9b-42a3-a5bb-e5a779530628.png', NOW(), NOW()),
                                                                                                                    (5, 3, 'Nguyễn Văn Thắng', 'HR Manager', 11, '/uploads/avatars/company-contact/11_a5ef3cd2-6ca8-436e-9e2c-ccb64eb069d0.png', NOW(), NOW()),
                                                                                                                    (6, 4, 'Phạm Thị Hà', 'HR Specialist', 12, '/uploads/avatars/company-contact/12_3289196d-1803-4dac-8473-e76d413f162e.png', NOW(), NOW()),
                                                                                                                    (7, 5, 'Vũ Minh Đức', 'Talent Acquisition Lead', 13, '/uploads/avatars/company-contact/13_ed8eea67-05fc-4e3b-8d59-de48399552b0.png', NOW(), NOW()),
                                                                                                                    (8, 6, 'Nguyễn Văn Toàn', 'HR Director', 14, '/uploads/avatars/company-contact/14_8ae074d5-1fa3-4cb8-8796-57eabe6fe0a6.png', NOW(), NOW()),
                                                                                                                    (9, 7, 'Phạm Thị Linh', 'Talent Acquisition Manager', 15, '/uploads/avatars/company-contact/15_66c94885-1514-42f5-805e-8ca0c45d3e7d.png', NOW(), NOW());

-- Insert students batch 2021 with auth_user_id 16-23
INSERT INTO students (id, auth_user_id, student_code, name, class_name, major, gender, birthday, address, cpa, english_level, skills, image_path, created_at, updated_at) VALUES
                                                                                                                                                                              (1, 16, '20216805', 'Nguyễn Tiến Dũng', 'KHMT03-K66', 'Khoa học máy tính', 'Male', '2003-05-15', 'Hà Nội', 3.6, 'Intermediate', 'Java, Spring Boot, Vue.js, Docker', '/uploads/avatars/student/16_a722bd59-d4fd-4f79-8d40-04c30e8d7a2a.png', NOW(), NOW()),
                                                                                                                                                                              (2, 17, '20216123', 'Dungntelcom', 'KHMT01-K66', 'Khoa học máy tính', 'Male', '2003-03-21', 'Hải Phòng', 3.8, 'Upper Intermediate', 'Java, ReactJS, Python, SQL', '/uploads/avatars/student/17_018eea07-ab74-4e53-909e-9fdd4f09a67d.png', NOW(), NOW()),
                                                                                                                                                                              (3, 18, '20216456', 'Nguyễn Thị Trang', 'KHMT02-K66', 'Khoa học máy tính', 'Female', '2003-08-10', 'Nam Định', 3.5, 'Intermediate', 'C/C++, Java, HTML/CSS, Node.js', '/uploads/avatars/student/18_565766af-6a63-4ddd-9f76-ce1f90800587.png', NOW(), NOW()),
                                                                                                                                                                              (4, 19, '20216789', 'Vũ Quang Minh', 'CNTT01-K66', 'Công nghệ thông tin', 'Male', '2003-02-28', 'Thái Bình', 3.7, 'Advanced', 'Python, Django, JavaScript, AWS', '/uploads/avatars/student/19_911db643-40cf-4408-9398-d45cfde65c4d.png', NOW(), NOW()),
                                                                                                                                                                              (5, 20, '20216012', 'Nguyễn Hoàng Sơn', 'CNTT02-K66', 'Công nghệ thông tin', 'Male', '2003-07-22', 'Hà Nội', 3.4, 'Intermediate', 'Java, Spring, Angular, MySQL', '/uploads/avatars/student/20_902bb0b7-7321-4e8c-b130-3cf666762e8d.png', NOW(), NOW()),
                                                                                                                                                                              (6, 21, '20216345', 'Nguyễn Văn Hiền', 'HTTT01-K66', 'Hệ thống thông tin', 'Male', '2003-11-05', 'Bắc Ninh', 3.9, 'Upper Intermediate', 'Java, PHP, React, MongoDB', '/uploads/avatars/student/21_a369f7fd-6fa4-4b6d-ba40-7e567cc8e757.png', NOW(), NOW()),
                                                                                                                                                                              (7, 22, '20216678', 'Nguyễn Văn Thành', 'HTTT02-K66', 'Hệ thống thông tin', 'Male', '2003-01-30', 'Hưng Yên', 3.2, 'Upper Intermediate', 'Java, Python, ReactJS, PostgreSQL', '/uploads/avatars/student/22_d8b61932-9a10-4a07-b3c5-93b201dde091.png', NOW(), NOW()),
                                                                                                                                                                              (8, 23, '20216901', 'Nguyễn Thị Lam', 'KTPM01-K66', 'Kỹ thuật phần mềm', 'Female', '2003-04-17', 'Hà Nội', 3.6, 'Advanced', 'Java, .NET, Angular, Oracle', '/uploads/avatars/student/23_2cf0eb97-0425-47bc-a2db-01afd865ed0c.png', NOW(), NOW());

-- Insert new students batch 2022
INSERT INTO students (id, auth_user_id, student_code, name, class_name, major, gender, birthday, address, cpa, english_level, skills, image_path, created_at, updated_at) VALUES
                                                                                                                                                                              (9, 24, '20226701', 'Nguyễn Thị Linh', 'KHMT01-K67', 'Khoa học máy tính', 'Female', '2004-06-12', 'Hà Nội', 3.7, 'Upper Intermediate', 'Python, Java, React, MongoDB', '/uploads/avatars/student/24_37d094aa-0335-4a90-bd63-895dfd9dc94f.png', NOW(), NOW()),
                                                                                                                                                                              (10, 25, '20226802', 'Đỗ Thanh Hoàng', 'KTPM02-K67', 'Kỹ thuật phần mềm', 'Male', '2004-09-25', 'Hải Dương', 3.5, 'Intermediate', 'C/C++, JavaScript, Node.js, MySQL', '/uploads/avatars/student/25_ae5a74ff-40fa-4795-bce0-6c6ef7e6c267.png', NOW(), NOW()),
                                                                                                                                                                              (11, 26, '20226903', 'Nguyễn Thị Thu', 'HTTT01-K67', 'Hệ thống thông tin', 'Female', '2004-03-18', 'Bắc Giang', 3.8, 'Advanced', 'Java, Spring Boot, Angular, PostgreSQL', '/uploads/avatars/student/26_fb09de1b-62e1-41cb-a7fb-f14f666dfc41.png', NOW(), NOW());